from PyQt5 import QtCore, QtGui, QtWidgets
# Sets up the input Screen Class GUI
class Ui_fileSave_popup(object):
    def setupUi(self, fileSave_popup):
        fileSave_popup.setObjectName("fileSave_popup")
        fileSave_popup.resize(971, 164)
        self.label = QtWidgets.QLabel(fileSave_popup)
        self.label.setGeometry(QtCore.QRect(370, 30, 261, 31))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.path_lable = QtWidgets.QLabel(fileSave_popup)
        self.path_lable.setGeometry(QtCore.QRect(20, 80, 921, 16))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.path_lable.setFont(font)
        self.path_lable.setText("")
        self.path_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.path_lable.setObjectName("path_lable")
        self.pushButton = QtWidgets.QPushButton(fileSave_popup)
        self.pushButton.setGeometry(QtCore.QRect(440, 120, 93, 28))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(fileSave_popup)
        QtCore.QMetaObject.connectSlotsByName(fileSave_popup)

    def retranslateUi(self, fileSave_popup):
        _translate = QtCore.QCoreApplication.translate
        fileSave_popup.setWindowTitle(_translate("fileSave_popup", "Dialog"))
        self.label.setText(_translate("fileSave_popup", "CSV File created at path:"))
        self.pushButton.setText(_translate("fileSave_popup", "Ok"))

class Ui_Input_Screen(object):
    def setupUi(self, Input_Screen):
        Input_Screen.setObjectName("Input_Screen")
        Input_Screen.resize(489, 162)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Input_Screen.sizePolicy().hasHeightForWidth())
        Input_Screen.setSizePolicy(sizePolicy)
        Input_Screen.setAutoFillBackground(False)
        self.splitter = QtWidgets.QSplitter(Input_Screen)
        self.splitter.setGeometry(QtCore.QRect(90, 40, 331, 31))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.ein_label = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ein_label.sizePolicy().hasHeightForWidth())
        self.ein_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.ein_label.setFont(font)
        self.ein_label.setObjectName("ein_label")
        self.ein_input = QtWidgets.QLineEdit(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ein_input.sizePolicy().hasHeightForWidth())
        self.ein_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.ein_input.setFont(font)
        self.ein_input.setObjectName("ein_input")
        self.find_btn = QtWidgets.QPushButton(Input_Screen)
        self.find_btn.setGeometry(QtCore.QRect(200, 90, 93, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.find_btn.sizePolicy().hasHeightForWidth())
        self.find_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.find_btn.setFont(font)
        self.find_btn.setObjectName("find_btn")

        self.retranslateUi(Input_Screen)
        QtCore.QMetaObject.connectSlotsByName(Input_Screen)

    def retranslateUi(self, Input_Screen):
        _translate = QtCore.QCoreApplication.translate
        Input_Screen.setWindowTitle(_translate("Input_Screen", "Dialog"))
        self.ein_label.setText(_translate("Input_Screen", "EIN #:"))
        self.ein_input.setPlaceholderText(_translate("Input_Screen", "XX-XXXXXXX"))
        self.find_btn.setText(_translate("Input_Screen", "Find"))

# sets up the error pop up class GUI
class Ui_EIN_error_popup(object):
    def setupUi(self, EIN_error_popup):
        EIN_error_popup.setObjectName("EIN_error_popup")
        EIN_error_popup.resize(283, 143)
        self.label = QtWidgets.QLabel(EIN_error_popup)
        self.label.setGeometry(QtCore.QRect(80, 40, 160, 20))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ok_btn = QtWidgets.QPushButton(EIN_error_popup)
        self.ok_btn.setGeometry(QtCore.QRect(90, 70, 93, 29))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.ok_btn.setFont(font)
        self.ok_btn.setObjectName("ok_btn")

        self.retranslateUi(EIN_error_popup)
        QtCore.QMetaObject.connectSlotsByName(EIN_error_popup)

    def retranslateUi(self, EIN_error_popup):
        _translate = QtCore.QCoreApplication.translate
        EIN_error_popup.setWindowTitle(_translate("EIN_error_popup", "Dialog"))
        self.label.setText(_translate("EIN_error_popup", "Invalid EIN"))
        self.ok_btn.setText(_translate("EIN_error_popup", "Ok"))

# Sets up the Results window GUI
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1061, 945)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 20, 861, 781))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.name_val = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.name_val.setFont(font)
        self.name_val.setText("")
        self.name_val.setObjectName("name_val")
        self.gridLayout.addWidget(self.name_val, 1, 1, 1, 1)
        self.ein_val = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ein_val.sizePolicy().hasHeightForWidth())
        self.ein_val.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.ein_val.setFont(font)
        self.ein_val.setText("")
        self.ein_val.setObjectName("ein_val")
        self.gridLayout.addWidget(self.ein_val, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.tableView = QtWidgets.QTableView(self.layoutWidget)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.graphic_dd = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphic_dd.sizePolicy().hasHeightForWidth())
        self.graphic_dd.setSizePolicy(sizePolicy)
        self.graphic_dd.setObjectName("graphic_dd")
        self.horizontalLayout_3.addWidget(self.graphic_dd)
        self.go_btn = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.go_btn.sizePolicy().hasHeightForWidth())
        self.go_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.go_btn.setFont(font)
        self.go_btn.setObjectName("go_btn")
        self.horizontalLayout_3.addWidget(self.go_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.widget = QtWidgets.QWidget(self.layoutWidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.csv_yes_btn = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csv_yes_btn.sizePolicy().hasHeightForWidth())
        self.csv_yes_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.csv_yes_btn.setFont(font)
        self.csv_yes_btn.setObjectName("csv_yes_btn")
        self.horizontalLayout_2.addWidget(self.csv_yes_btn)
        self.csv_no_button = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csv_no_button.sizePolicy().hasHeightForWidth())
        self.csv_no_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.csv_no_button.setFont(font)
        self.csv_no_button.setObjectName("csv_no_button")
        self.horizontalLayout_2.addWidget(self.csv_no_button, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.widget1, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.widget, 0, QtCore.Qt.AlignHCenter)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(230, 830, 571, 71))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1061, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "EIN #:"))
        self.label_3.setText(_translate("MainWindow", "Name:"))
        self.label_2.setText(_translate("MainWindow", "Generate Graphics"))
        self.go_btn.setText(_translate("MainWindow", "Go"))
        self.label_5.setText(_translate("MainWindow", "Would you like to store the csv file?"))
        self.csv_yes_btn.setText(_translate("MainWindow", "Yes"))
        self.csv_no_button.setText(_translate("MainWindow", "No"))

# Sets up the Secondary Window Screen
class Ui_Interval_Screen(object):
    def setupUi(self, Interval_Screen):
        Interval_Screen.setObjectName("Interval_Screen")
        Interval_Screen.resize(551, 312)
        self.run_btn2 = QtWidgets.QPushButton(Interval_Screen)
        self.run_btn2.setGeometry(QtCore.QRect(230, 230, 93, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_btn2.sizePolicy().hasHeightForWidth())
        self.run_btn2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.run_btn2.setFont(font)
        self.run_btn2.setObjectName("run_btn2")
        self.layoutWidget = QtWidgets.QWidget(Interval_Screen)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 40, 511, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ein_label2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.ein_label2.setFont(font)
        self.ein_label2.setAcceptDrops(False)
        self.ein_label2.setAlignment(QtCore.Qt.AlignCenter)
        self.ein_label2.setObjectName("ein_label2")
        self.horizontalLayout.addWidget(self.ein_label2)
        self.ein_val = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ein_val.sizePolicy().hasHeightForWidth())
        self.ein_val.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.ein_val.setFont(font)
        self.ein_val.setAcceptDrops(False)
        self.ein_val.setText("")
        self.ein_val.setAlignment(QtCore.Qt.AlignCenter)
        self.ein_val.setObjectName("ein_val")
        self.horizontalLayout.addWidget(self.ein_val)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.name_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.name_label.setFont(font)
        self.name_label.setAcceptDrops(False)
        self.name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.horizontalLayout_2.addWidget(self.name_label)
        self.name_val = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_val.sizePolicy().hasHeightForWidth())
        self.name_val.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.name_val.setFont(font)
        self.name_val.setAcceptDrops(False)
        self.name_val.setLineWidth(1)
        self.name_val.setText("")
        self.name_val.setAlignment(QtCore.Qt.AlignCenter)
        self.name_val.setObjectName("name_val")
        self.horizontalLayout_2.addWidget(self.name_val)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Interval_Screen)
        QtCore.QMetaObject.connectSlotsByName(Interval_Screen)

    def retranslateUi(self, Interval_Screen):
        _translate = QtCore.QCoreApplication.translate
        Interval_Screen.setWindowTitle(_translate("Interval_Screen", "Dialog"))
        self.run_btn2.setText(_translate("Interval_Screen", "Run"))
        self.ein_label2.setText(_translate("Interval_Screen", "EIN #:"))
        self.name_label.setText(_translate("Interval_Screen", "Name:"))

